# Generated by Django 6.0.4 on 2026-05-02 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novel'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['novel', 'chapter_number'], name='chapters_ch_novel_i_9a4094_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['novel', 'status', 'chapter_number'], name='chapters_ch_novel_i_91c81d_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['status', 'published_at'], name='chapters_ch_status_3f06da_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['audit_status'], name='chapters_ch_audit_s_8522ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('novel', 'chapter_number'), name='unique_chapter_number_per_novel'),
        ),
    ]
