# Generated by Django 6.0.4 on 2026-05-04 04:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_initial'),
        ('novels', '0005_alter_category_options_alter_novel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['novel_id', 'chapter_number'], 'verbose_name': '章节', 'verbose_name_plural': '章节管理'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='audit_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(verbose_name='章节序号'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(verbose_name='章节正文'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_free',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否免费'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novel', verbose_name='所属小说'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], db_index=True, default='draft', max_length=20, verbose_name='章节状态'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='章节标题'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='word_count',
            field=models.PositiveIntegerField(default=0, verbose_name='章节字数'),
        ),
    ]
