# Generated by Django 6.0.4 on 2026-05-04 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_alter_chapter_audit_status'),
        ('novels', '0007_novel_reviewed_at_novel_reviewer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='审核完成时间'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_chapters', to=settings.AUTH_USER_MODEL, verbose_name='审核员'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['audit_status', 'reviewer'], name='chapters_ch_audit_s_0f97b9_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['reviewer', 'reviewed_at'], name='chapters_ch_reviewe_cd2b9e_idx'),
        ),
    ]
