# Generated by Django 6.0.4 on 2026-05-02 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('like_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('hidden', 'Hidden'), ('deleted', 'Deleted')], db_index=True, default='normal', max_length=20)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='chapters.chapter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
