# Generated by Django 6.0.4 on 2026-05-04 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_alter_chapter_options_alter_chapter_audit_status_and_more'),
        ('comments', '0003_initial'),
        ('novels', '0005_alter_category_options_alter_novel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': '评论', 'verbose_name_plural': '评论管理'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='chapters.chapter', verbose_name='章节'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='novels.novel', verbose_name='小说'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='comments.comment', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('hidden', '已隐藏'), ('deleted', '已删除')], db_index=True, default='normal', max_length=20, verbose_name='评论状态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
