# Generated by Django 6.0.4 on 2026-05-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_avatar_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', '读者'), ('author', '作者'), ('reviewer', '审核员'), ('admin', '管理员')], db_index=True, default='reader', max_length=20, verbose_name='用户角色'),
        ),
    ]
