from django.urls import path

from .views import (
    AdminCategoryDetailView,
    AdminCategoryListCreateView,
    AdminCategoryStatusView,
    AdminNovelApproveView,
    AdminNovelDetailView,
    AdminNovelFeaturedView,
    AdminNovelListView,
    AdminNovelRejectView,
    AdminNovelStatusView,
    AdminPendingNovelListView,
    AuthorNovelDetailView,
    AuthorNovelListCreateView,
    AuthorNovelSubmitView,
    CategoryListView,
    NovelDetailView,
    NovelListView,
    NovelRatingSummaryView,
    NovelRatingView,
    ReviewerAuditLogListView,
    ReviewerNovelApproveView,
    ReviewerNovelClaimView,
    ReviewerNovelDetailView,
    ReviewerNovelRejectView,
    ReviewerPendingNovelListView,
    ReviewerReviewingNovelListView,
)

app_name = "novels"

urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("admin/categories/", AdminCategoryListCreateView.as_view(), name="admin-category-list-create"),
    path("admin/categories/<int:id>/status/", AdminCategoryStatusView.as_view(), name="admin-category-status"),
    path("admin/categories/<int:id>/", AdminCategoryDetailView.as_view(), name="admin-category-detail"),
    path("novels/", NovelListView.as_view(), name="novel-list"),
    path("novels/<int:id>/", NovelDetailView.as_view(), name="novel-detail"),
    path("novels/<int:novel_id>/ratings/summary/", NovelRatingSummaryView.as_view(), name="novel-rating-summary"),
    path("novels/<int:novel_id>/ratings/", NovelRatingView.as_view(), name="novel-rating"),
    path("author/novels/", AuthorNovelListCreateView.as_view(), name="author-novel-list-create"),
    path("author/novels/<int:id>/", AuthorNovelDetailView.as_view(), name="author-novel-detail"),
    path("author/novels/<int:id>/submit/", AuthorNovelSubmitView.as_view(), name="author-novel-submit"),
    path("admin/novels/pending/", AdminPendingNovelListView.as_view(), name="admin-novel-pending-list"),
    path("admin/novels/", AdminNovelListView.as_view(), name="admin-novel-list"),
    path("admin/novels/<int:id>/status/", AdminNovelStatusView.as_view(), name="admin-novel-status"),
    path("admin/novels/<int:id>/featured/", AdminNovelFeaturedView.as_view(), name="admin-novel-featured"),
    path("admin/novels/<int:id>/", AdminNovelDetailView.as_view(), name="admin-novel-detail"),
    path("admin/novels/<int:id>/approve/", AdminNovelApproveView.as_view(), name="admin-novel-approve"),
    path("admin/novels/<int:id>/reject/", AdminNovelRejectView.as_view(), name="admin-novel-reject"),
    path("reviewer/novels/pending/", ReviewerPendingNovelListView.as_view(), name="reviewer-novel-pending-list"),
    path("reviewer/novels/reviewing/", ReviewerReviewingNovelListView.as_view(), name="reviewer-novel-reviewing-list"),
    path("reviewer/novels/<int:id>/", ReviewerNovelDetailView.as_view(), name="reviewer-novel-detail"),
    path("reviewer/novels/<int:id>/claim/", ReviewerNovelClaimView.as_view(), name="reviewer-novel-claim"),
    path("reviewer/novels/<int:id>/approve/", ReviewerNovelApproveView.as_view(), name="reviewer-novel-approve"),
    path("reviewer/novels/<int:id>/reject/", ReviewerNovelRejectView.as_view(), name="reviewer-novel-reject"),
    path("reviewer/audit-logs/", ReviewerAuditLogListView.as_view(), name="reviewer-audit-log-list"),
]
