from django.urls import path

from .views import (
    AdminVideoProjectDetailView,
    AdminVideoProjectListView,
    VideoAssetAudioReviewView,
    VideoAssetDownloadView,
    VideoAssetVisualReviewView,
    VideoProjectAiStoryboardView,
    VideoProjectChapterCreateView,
    VideoProjectCapabilitiesView,
    VideoProjectDetailView,
    VideoProjectListCreateView,
    VideoProjectNovelCreateView,
    VideoProjectStoryboardView,
    VideoProjectStoryboardJobView,
    VideoProjectSubtitleAssetView,
    VideoProjectLatestStoryboardJobView,
    VideoProjectImageAssetJobView,
    VideoProjectVideoClipJobView,
    VideoProjectNarrationAudioJobView,
    VideoProjectRenderJobView,
    VideoGenerationJobDetailView,
    VideoGenerationJobRetryView,
    VideoSceneDetailView,
    VideoStoryDraftView,
    VideoSourceChapterListView,
    VideoSourceNovelListView,
)

app_name = "video_generation"

urlpatterns = [
    path("video-source-chapters/", VideoSourceChapterListView.as_view(), name="video-source-chapter-list"),
    path("video-source-novels/", VideoSourceNovelListView.as_view(), name="video-source-novel-list"),
    path("video-projects/capabilities/", VideoProjectCapabilitiesView.as_view(), name="video-project-capabilities"),
    path("video-projects/story-draft/", VideoStoryDraftView.as_view(), name="video-story-draft"),
    path("video-projects/from-chapter/", VideoProjectChapterCreateView.as_view(), name="video-project-chapter-create"),
    path("video-projects/from-novel/", VideoProjectNovelCreateView.as_view(), name="video-project-novel-create"),
    path("video-projects/", VideoProjectListCreateView.as_view(), name="video-project-list-create"),
    path("video-projects/<int:id>/storyboard/", VideoProjectStoryboardView.as_view(), name="video-project-storyboard"),
    path("video-projects/<int:id>/storyboard/ai/", VideoProjectAiStoryboardView.as_view(), name="video-project-ai-storyboard"),
    path("video-projects/<int:id>/storyboard/jobs/", VideoProjectStoryboardJobView.as_view(), name="video-project-storyboard-job-create"),
    path("video-projects/<int:id>/storyboard/jobs/latest/", VideoProjectLatestStoryboardJobView.as_view(), name="video-project-storyboard-job-latest"),
    path("video-projects/<int:id>/assets/subtitles/", VideoProjectSubtitleAssetView.as_view(), name="video-project-subtitle-asset"),
    path("video-projects/<int:id>/assets/images/jobs/", VideoProjectImageAssetJobView.as_view(), name="video-project-image-asset-job"),
    path("video-projects/<int:id>/assets/videos/jobs/", VideoProjectVideoClipJobView.as_view(), name="video-project-video-clip-job"),
    path("video-projects/<int:id>/assets/audio/jobs/", VideoProjectNarrationAudioJobView.as_view(), name="video-project-audio-asset-job"),
    path("video-projects/<int:id>/render/jobs/", VideoProjectRenderJobView.as_view(), name="video-project-render-job"),
    path("video-projects/<int:id>/scenes/<int:scene_id>/", VideoSceneDetailView.as_view(), name="video-scene-detail"),
    path("video-projects/<int:id>/", VideoProjectDetailView.as_view(), name="video-project-detail"),
    path("video-generation-jobs/<int:id>/", VideoGenerationJobDetailView.as_view(), name="video-generation-job-detail"),
    path("video-generation-jobs/<int:id>/retry/", VideoGenerationJobRetryView.as_view(), name="video-generation-job-retry"),
    path("video-assets/<int:id>/audio-review/", VideoAssetAudioReviewView.as_view(), name="video-asset-audio-review"),
    path("video-assets/<int:id>/visual-review/", VideoAssetVisualReviewView.as_view(), name="video-asset-visual-review"),
    path("video-assets/<int:id>/download/", VideoAssetDownloadView.as_view(), name="video-asset-download"),
    path("admin/video-projects/", AdminVideoProjectListView.as_view(), name="admin-video-project-list"),
    path("admin/video-projects/<int:id>/", AdminVideoProjectDetailView.as_view(), name="admin-video-project-detail"),
]
