# Generated by Django 6.0.4 on 2026-05-02 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelf', '0003_initial'),
        ('chapters', '0002_initial'),
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_histories', to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_histories', to='novels.novel'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookshelf',
            index=models.Index(fields=['user', 'last_read_at'], name='bookshelf_b_user_id_8385c2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookshelf',
            index=models.Index(fields=['novel'], name='bookshelf_b_novel_i_4836de_idx'),
        ),
        migrations.AddIndex(
            model_name='bookshelf',
            index=models.Index(fields=['last_read_chapter'], name='bookshelf_b_last_re_fed84f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookshelf',
            constraint=models.UniqueConstraint(fields=('user', 'novel'), name='unique_bookshelf_user_novel'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['user', 'read_at'], name='bookshelf_r_user_id_816ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['novel', 'read_at'], name='bookshelf_r_novel_i_57acfa_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['chapter', 'read_at'], name='bookshelf_r_chapter_0a48b3_idx'),
        ),
    ]
