# Generated by Django 6.0.4 on 2026-05-04 04:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_initial'),
        ('chapters', '0003_alter_chapter_options_alter_chapter_audit_status_and_more'),
        ('novels', '0005_alter_category_options_alter_novel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookshelf',
            options={'verbose_name': '书架', 'verbose_name_plural': '书架管理'},
        ),
        migrations.AlterModelOptions(
            name='readinghistory',
            options={'ordering': ['-read_at'], 'verbose_name': '阅读历史', 'verbose_name_plural': '阅读历史管理'},
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='last_read_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='最近阅读时间'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='last_read_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookshelf_entries', to='chapters.chapter', verbose_name='最近阅读章节'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf_entries', to='novels.novel', verbose_name='小说'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='reading_progress',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='阅读进度'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelves', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_histories', to='chapters.chapter', verbose_name='章节'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_histories', to='novels.novel', verbose_name='小说'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='阅读时间'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='reading_position',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读位置'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_histories', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
