# Generated by Django 6.0.4 on 2026-05-04 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('novel', '小说'), ('chapter', '章节')], db_index=True, max_length=20, verbose_name='审核对象类型')),
                ('object_id', models.PositiveBigIntegerField(db_index=True, verbose_name='审核对象 ID')),
                ('action', models.CharField(choices=[('submit', '提交审核'), ('claim', '领取审核'), ('approve', '审核通过'), ('reject', '审核驳回')], db_index=True, max_length=20, verbose_name='操作类型')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='原审核状态')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='新审核状态')),
                ('reason', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='审核员')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录管理',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'created_at'], name='common_audi_content_94efdc_idx'), models.Index(fields=['reviewer', 'action', 'created_at'], name='common_audi_reviewe_7d0ef0_idx'), models.Index(fields=['action', 'created_at'], name='common_audi_action_f07e2b_idx')],
            },
        ),
    ]
