# Generated by Django 6.0.4 on 2026-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('submit', '提交审核'), ('claim', '领取审核'), ('approve', '审核通过'), ('reject', '审核驳回'), ('create', '创建'), ('update', '更新'), ('status_update', '状态变更'), ('feature_update', '推荐变更'), ('role_update', '角色变更'), ('ban', '封禁'), ('unban', '解封')], db_index=True, max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.CharField(choices=[('novel', '小说'), ('chapter', '章节'), ('user', '用户'), ('category', '分类'), ('comment', '评论'), ('ranking_type', '榜单类型'), ('ranking_item', '榜单条目')], db_index=True, max_length=20, verbose_name='审核对象类型'),
        ),
    ]
