# Generated by Django 6.0.4 on 2026-07-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_auditlog_action_alter_auditlog_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.CharField(choices=[('novel', '小说'), ('chapter', '章节'), ('user', '用户'), ('category', '分类'), ('comment', '评论'), ('ranking_type', '榜单类型'), ('ranking_item', '榜单条目'), ('video_project', 'Video project'), ('video_scene', 'Video scene'), ('video_job', 'Video generation job')], db_index=True, max_length=20, verbose_name='审核对象类型'),
        ),
    ]
