# Generated by Django 6.0.4 on 2026-05-02 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novels', to='novels.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'sort_order'], name='novels_cate_parent__947ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'sort_order'], name='novels_cate_is_acti_e468d4_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['author', 'status'], name='novels_nove_author__448fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['category', 'status'], name='novels_nove_categor_cbe501_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['status', 'audit_status'], name='novels_nove_status_528b32_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['is_featured', 'audit_status'], name='novels_nove_is_feat_d013a1_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['-view_count'], name='novels_nove_view_co_a5b992_idx'),
        ),
    ]
