# Generated by Django 6.0.4 on 2026-05-02 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='rating_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='NovelRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['novel', 'score'], name='novels_nove_novel_i_8e2dba_idx'), models.Index(fields=['user', 'created_at'], name='novels_nove_user_id_e126de_idx'), models.Index(fields=['novel', 'created_at'], name='novels_nove_novel_i_a2e9c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'novel'), name='unique_novel_rating_user_novel'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='novel_rating_score_between_1_and_5')],
            },
        ),
    ]
