# Generated by Django 6.0.4 on 2026-05-04 04:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_recalculate_rating_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': '分类', 'verbose_name_plural': '分类管理'},
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ['-latest_chapter_updated_at', '-created_at'], 'verbose_name': '小说', 'verbose_name_plural': '小说管理'},
        ),
        migrations.AlterModelOptions(
            name='novelrating',
            options={'verbose_name': '小说评分', 'verbose_name_plural': '小说评分管理'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='novels.category', verbose_name='父分类'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='分类标识'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='排序值'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='audit_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], db_index=True, default='draft', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novels', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novels', to='novels.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='collect_count',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.URLField(blank=True, max_length=500, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='latest_chapter_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='最新章节标题'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='latest_chapter_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='最新章节更新时间'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='rating_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='评分人数'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='rating_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='平均评分'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('serializing', '连载中'), ('completed', '已完结'), ('paused', '暂停更新'), ('removed', '已下架')], db_index=True, default='serializing', max_length=20, verbose_name='连载状态'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='小说标题'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='word_count',
            field=models.PositiveIntegerField(default=0, verbose_name='字数'),
        ),
        migrations.AlterField(
            model_name='novelrating',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='短评'),
        ),
        migrations.AlterField(
            model_name='novelrating',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='novels.novel', verbose_name='小说'),
        ),
        migrations.AlterField(
            model_name='novelrating',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 分'), (2, '2 分'), (3, '3 分'), (4, '4 分'), (5, '5 分')], db_index=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='novelrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_ratings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
