# Generated by Django 6.0.4 on 2026-05-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_category_options_alter_novel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='audit_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='draft', max_length=20, verbose_name='审核状态'),
        ),
    ]
