# Generated by Django 6.0.4 on 2026-05-04 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_alter_novel_audit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='审核完成时间'),
        ),
        migrations.AddField(
            model_name='novel',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_novels', to=settings.AUTH_USER_MODEL, verbose_name='审核员'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['audit_status', 'reviewer'], name='novels_nove_audit_s_ca0a28_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['reviewer', 'reviewed_at'], name='novels_nove_reviewe_373623_idx'),
        ),
    ]
