# Generated by Django 6.0.4 on 2026-07-10 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0005_chapter_reviewed_at_chapter_reviewer_and_more'),
        ('novels', '0007_novel_reviewed_at_novel_reviewer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('text', 'Text'), ('chapter', 'Chapter'), ('novel', 'Novel')], db_index=True, default='text', max_length=20, verbose_name='Source type')),
                ('source_title', models.CharField(blank=True, max_length=255, verbose_name='Source title')),
                ('source_excerpt_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Source excerpt hash')),
                ('input_text', models.TextField(blank=True, verbose_name='Input text')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Project title')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('style_preset', models.CharField(default='cinematic_story', max_length=64, verbose_name='Style preset')),
                ('duration_target', models.PositiveSmallIntegerField(default=60, verbose_name='Duration target seconds')),
                ('aspect_ratio', models.CharField(default='9:16', max_length=20, verbose_name='Aspect ratio')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('storyboard_ready', 'Storyboard ready'), ('asset_generating', 'Asset generating'), ('rendering', 'Rendering'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=30, verbose_name='Status')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Failure reason')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_projects', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('source_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_projects', to='chapters.chapter', verbose_name='Source chapter')),
                ('source_novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_projects', to='novels.novel', verbose_name='Source novel')),
            ],
            options={
                'verbose_name': 'Video project',
                'verbose_name_plural': 'Video projects',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VideoScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene_no', models.PositiveSmallIntegerField(verbose_name='Scene number')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Scene title')),
                ('visual_prompt', models.TextField(blank=True, verbose_name='Visual prompt')),
                ('narration_text', models.TextField(blank=True, verbose_name='Narration text')),
                ('subtitle_text', models.TextField(blank=True, verbose_name='Subtitle text')),
                ('duration_seconds', models.PositiveSmallIntegerField(default=8, verbose_name='Duration seconds')),
                ('camera_direction', models.CharField(blank=True, max_length=200, verbose_name='Camera direction')),
                ('mood', models.CharField(blank=True, max_length=100, verbose_name='Mood')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Failure reason')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='video_generation.videoproject', verbose_name='Video project')),
            ],
            options={
                'verbose_name': 'Video scene',
                'verbose_name_plural': 'Video scenes',
                'ordering': ['project_id', 'scene_no'],
            },
        ),
        migrations.AddIndex(
            model_name='videoproject',
            index=models.Index(fields=['owner', 'status'], name='video_gener_owner_i_9e69b2_idx'),
        ),
        migrations.AddIndex(
            model_name='videoproject',
            index=models.Index(fields=['owner', 'created_at'], name='video_gener_owner_i_64e2df_idx'),
        ),
        migrations.AddIndex(
            model_name='videoproject',
            index=models.Index(fields=['source_type', 'created_at'], name='video_gener_source__a73b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='videoproject',
            index=models.Index(fields=['status', 'created_at'], name='video_gener_status_35146b_idx'),
        ),
        migrations.AddIndex(
            model_name='videoproject',
            index=models.Index(fields=['deleted_at', 'created_at'], name='video_gener_deleted_cdddae_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoproject',
            constraint=models.CheckConstraint(condition=models.Q(('duration_target__gte', 30), ('duration_target__lte', 90)), name='video_project_duration_target_range'),
        ),
        migrations.AddIndex(
            model_name='videoscene',
            index=models.Index(fields=['project', 'scene_no'], name='video_gener_project_5b375c_idx'),
        ),
        migrations.AddIndex(
            model_name='videoscene',
            index=models.Index(fields=['project', 'status'], name='video_gener_project_569b7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoscene',
            constraint=models.UniqueConstraint(fields=('project', 'scene_no'), name='unique_video_scene_no_per_project'),
        ),
        migrations.AddConstraint(
            model_name='videoscene',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gt', 0)), name='video_scene_duration_positive'),
        ),
    ]
