# Generated by Django 6.0.4 on 2026-07-12 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('ai_storyboard', 'AI storyboard')], db_index=True, default='ai_storyboard', max_length=30, verbose_name='Job type')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=20, verbose_name='Status')),
                ('provider', models.CharField(default='openai_compatible', max_length=50, verbose_name='Provider')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='Model name')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Request payload')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='Attempt count')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='Max attempts')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='video_generation.videoproject', verbose_name='Video project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_generation_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
            options={
                'verbose_name': 'Video generation job',
                'verbose_name_plural': 'Video generation jobs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='video_gener_status_dc93c1_idx'), models.Index(fields=['project', 'status'], name='video_gener_project_f250ba_idx'), models.Index(fields=['job_type', 'status', 'created_at'], name='video_gener_job_typ_d0850b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1), ('max_attempts__lte', 5)), name='video_job_max_attempts_range'), models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='video_job_attempt_within_limit'), models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('project', 'job_type'), name='unique_active_video_job_per_project_type')],
            },
        ),
    ]
