# Generated by Django 6.0.4 on 2026-07-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generation', '0002_videogenerationjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('subtitle', 'Subtitle')], db_index=True, max_length=20, verbose_name='Asset type')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('stale', 'Stale'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20, verbose_name='Status')),
                ('storage_path', models.CharField(blank=True, max_length=500, verbose_name='Storage path')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='File name')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='File size')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Provider')),
                ('provider_asset_id', models.CharField(blank=True, max_length=255, verbose_name='Provider asset ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Failure reason')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='video_generation.videoproject', verbose_name='Video project')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='video_generation.videoscene', verbose_name='Video scene')),
            ],
            options={
                'verbose_name': 'Video asset',
                'verbose_name_plural': 'Video assets',
                'ordering': ['project_id', 'asset_type', 'scene_id', 'id'],
                'indexes': [models.Index(fields=['project', 'asset_type', 'status'], name='video_gener_project_73ed19_idx'), models.Index(fields=['scene', 'asset_type'], name='video_gener_scene_i_0b47a5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('asset_type', 'subtitle'), ('scene__isnull', True)), models.Q(('asset_type__in', ('image', 'audio')), ('scene__isnull', False)), _connector='OR'), name='video_asset_scope_matches_type'), models.UniqueConstraint(condition=models.Q(('scene__isnull', False)), fields=('project', 'scene', 'asset_type'), name='unique_video_scene_asset_type'), models.UniqueConstraint(condition=models.Q(('scene__isnull', True)), fields=('project', 'asset_type'), name='unique_video_project_asset_type')],
            },
        ),
    ]
