# Generated by Django 6.0.4 on 2026-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generation', '0003_videoasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogenerationjob',
            name='job_type',
            field=models.CharField(choices=[('ai_storyboard', 'AI storyboard'), ('image_assets', 'Image assets'), ('narration_audio', 'Narration audio')], db_index=True, default='ai_storyboard', max_length=30, verbose_name='Job type'),
        ),
    ]
