# Generated by Django 6.0.4 on 2026-07-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generation', '0005_remove_videoasset_video_asset_scope_matches_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videoasset',
            name='video_asset_scope_matches_type',
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='asset_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('subtitle', 'Subtitle'), ('final_video', 'Final video')], db_index=True, max_length=20, verbose_name='Asset type'),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='job_type',
            field=models.CharField(choices=[('ai_storyboard', 'AI storyboard'), ('image_assets', 'Image assets'), ('video_clips', 'Video clips'), ('narration_audio', 'Narration audio'), ('render', 'Render')], db_index=True, default='ai_storyboard', max_length=30, verbose_name='Job type'),
        ),
        migrations.AddConstraint(
            model_name='videoasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset_type__in', ('subtitle', 'final_video')), ('scene__isnull', True)), models.Q(('asset_type__in', ('image', 'video', 'audio')), ('scene__isnull', False)), _connector='OR'), name='video_asset_scope_matches_type'),
        ),
    ]
