# Generated by Django 6.0.4 on 2026-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generation', '0006_remove_videoasset_video_asset_scope_matches_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='agent_workflow',
            field=models.JSONField(blank=True, default=dict, verbose_name='Agent workflow'),
        ),
        migrations.AddField(
            model_name='videoscene',
            name='agent_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Agent metadata'),
        ),
    ]
