# Generated by Django 6.0.4 on 2026-05-02 03:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_active', 'code'], name='rankings_ra_is_acti_53ad83_idx')],
            },
        ),
        migrations.CreateModel(
            name='RankingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('calculated_at', models.DateTimeField(db_index=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_items', to='novels.novel')),
                ('ranking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rankings.rankingtype')),
            ],
            options={
                'ordering': ['ranking_type_id', 'rank'],
                'indexes': [models.Index(fields=['ranking_type', 'rank'], name='rankings_ra_ranking_83620a_idx'), models.Index(fields=['ranking_type', 'calculated_at'], name='rankings_ra_ranking_cccf6e_idx'), models.Index(fields=['novel'], name='rankings_ra_novel_i_8db3cc_idx'), models.Index(fields=['-score'], name='rankings_ra_score_d6dfc1_idx')],
                'constraints': [models.UniqueConstraint(fields=('ranking_type', 'novel', 'calculated_at'), name='unique_ranking_item_per_snapshot'), models.UniqueConstraint(fields=('ranking_type', 'rank', 'calculated_at'), name='unique_ranking_rank_per_snapshot')],
            },
        ),
    ]
