# Generated by Django 6.0.4 on 2026-05-04 04:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_category_options_alter_novel_options_and_more'),
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingitem',
            options={'ordering': ['ranking_type_id', 'rank'], 'verbose_name': '榜单条目', 'verbose_name_plural': '榜单条目管理'},
        ),
        migrations.AlterModelOptions(
            name='rankingtype',
            options={'ordering': ['code'], 'verbose_name': '榜单类型', 'verbose_name_plural': '榜单类型管理'},
        ),
        migrations.AlterField(
            model_name='rankingitem',
            name='calculated_at',
            field=models.DateTimeField(db_index=True, verbose_name='计算时间'),
        ),
        migrations.AlterField(
            model_name='rankingitem',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_items', to='novels.novel', verbose_name='小说'),
        ),
        migrations.AlterField(
            model_name='rankingitem',
            name='rank',
            field=models.PositiveIntegerField(db_index=True, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='rankingitem',
            name='ranking_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rankings.rankingtype', verbose_name='榜单类型'),
        ),
        migrations.AlterField(
            model_name='rankingitem',
            name='score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='rankingtype',
            name='code',
            field=models.SlugField(max_length=100, unique=True, verbose_name='榜单编码'),
        ),
        migrations.AlterField(
            model_name='rankingtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='rankingtype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='rankingtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='榜单名称'),
        ),
    ]
